{% set name = "scvi-tools" %}
{% set version = "0.20.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2ec2643d2de9e474514b00129a9b473eea407bd86ef07b9e2b39c15bf780b1a3

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - python >=3.8
    - hatch
    - pip >=22.0
  run:
    - python >=3.8
    - anndata >=0.7.5
    - docrep >=0.3.2
    - h5py >=2.9.0
    - numpy >=1.17.0
    - openpyxl >=3.0
    - pandas >=1.0
    - pyro-ppl >=1.6.0
    - pytorch-lightning >=1.9.0,<1.10.0
    - rich >=12.0.0
    - scikit-learn >=0.21.2
    - pytorch >=1.8.0
    - tqdm >=4.56.0
    - jax >=0.3.0
    - jaxlib >=0.3.0
    - optax
    - numpyro >=0.9.0
    - flax >=0.4.0
    - torchmetrics >=0.11.0
    - mudata >=0.1.2
    - ml-collections >=0.1.1

test:
  imports:
    - scvi
    - scvi.model
    - scvi.nn
    - scvi.train
    - scvi.external
    - scvi.dataloaders
    - scvi.data
    - scvi.distributions
  requires:
    - pytest

about:
  home: https://scvi-tools.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Deep probabilistic analysis of single-cell omics data.
  doc_url: https://docs.scvi-tools.org/en/stable/
  dev_url: https://github.com/YosefLab/scvi-tools

extra:
  recipe-maintainers:
    - martinkim0
    - romain-lopez
    - adamgayoso
    - galenxing
    - justjhong
    - watiss
