{% set name = "scvi-tools" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e4b61ac7cc679fc48f487e8ade030ccd9c7a0fa4f603d5f3ca8327d57d3a764c

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - python >=3.9
    - hatch
    - pip >=22.0
  run:
    - python >=3.9
    - anndata >=0.7.5
    - docrep >=0.3.2
    - h5py >=2.9.0
    - numpy >=1.17.0
    - openpyxl >=3.0
    - pandas >=1.0
    - pyro-ppl >=1.6.0
    - lightning >=2.0,<2.1
    - rich >=12.0.0
    - scikit-learn >=0.21.2
    - pytorch >=1.8.0
    - tqdm >=4.56.0
    - jax >=0.4.4
    - jaxlib >=0.4.3
    - optax
    - numpyro >=0.12.1
    - flax >=0.4.0
    - torchmetrics >=0.11.0
    - mudata >=0.1.2
    - ml-collections >=0.1.1
    - sparse >=0.14.0
    - xarray >=2023.2.0

test:
  imports:
    - scvi
    - scvi.model
    - scvi.nn
    - scvi.train
    - scvi.external
    - scvi.dataloaders
    - scvi.data
    - scvi.distributions
  requires:
    - pytest

about:
  home: https://scvi-tools.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Deep probabilistic analysis of single-cell omics data.
  doc_url: https://docs.scvi-tools.org/en/stable/
  dev_url: https://github.com/YosefLab/scvi-tools

extra:
  recipe-maintainers:
    - martinkim0
    - romain-lopez
    - adamgayoso
    - galenxing
    - justjhong
    - watiss
