{% set python_min = "3.12" %}
{% set name = "scvi-tools" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 413cab3a8b8865bb42712c1239ab3b1e78960e0739df844128d3577c1556fb18

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch
    - pip >=22.0
  run:
    - joblib
    - python >={{ python_min }}
    - anndata
    - docrep >=0.3.2
    - numpy
    - pandas
    - pyro-ppl
    - lightning >=2
    - rich
    - scikit-learn
    - pytorch
    - tqdm
    - torchmetrics
    - mudata
    - scanpy >=1.10
    - ml-collections
    - sparse >=0.14
    - xarray
    - tensorboard
    - scipy
    - numba >=0.60

test:
  imports:
    - scvi
    - scvi.model
    - scvi.nn
    - scvi.train
    - scvi.external
    - scvi.dataloaders
    - scvi.data
    - scvi.distributions
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://scvi-tools.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Deep probabilistic analysis of single-cell omics data.
  doc_url: https://docs.scvi-tools.org/en/stable/
  dev_url: https://github.com/YosefLab/scvi-tools

extra:
  recipe-maintainers:
    - jdblischak
    - ori-kron-wis
    - canergen
    - martinkim0
    - romain-lopez
    - adamgayoso
    - galenxing
    - justjhong
    - watiss
