{% set python_min = "3.11" %}
{% set name = "scvi-tools" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cbbb253b941f4307d59d22e3e50111a3e5be3e9c2424a9571f7d4988da392c66

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch
    - pip >=22.0
  run:
    - python >={{ python_min }}
    - anndata >=0.11
    - docrep >=0.3.2
    - numpy
    - pandas
    - pyro-ppl
    - lightning >=2.0
    - rich
    - scikit-learn
    - pytorch
    - tqdm
    - torchmetrics
    - mudata
    - scanpy >=1.10
    - ml-collections
    - sparse >=0.14.0
    - xarray
    - tensorboard
    - scipy
    - numba >=0.60.0

test:
  imports:
    - scvi
    - scvi.model
    - scvi.nn
    - scvi.train
    - scvi.external
    - scvi.dataloaders
    - scvi.data
    - scvi.distributions
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://scvi-tools.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Deep probabilistic analysis of single-cell omics data.
  doc_url: https://docs.scvi-tools.org/en/stable/
  dev_url: https://github.com/YosefLab/scvi-tools

extra:
  recipe-maintainers:
    - jdblischak
    - ori-kron-wis
    - canergen
    - martinkim0
    - romain-lopez
    - adamgayoso
    - galenxing
    - justjhong
    - watiss
